import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
  <meta charSet="utf-8" />
  <title>Cartzilla | Checkout</title>
  {/* SEO Meta Tags*/}
  <meta name="description" content="Cartzilla - Bootstrap E-commerce Template" />
  <meta name="keywords" content="bootstrap, shop, e-commerce, market, modern, responsive,  business, mobile, bootstrap, html5, css3, js, gallery, slider, touch, creative, clean" />
  <meta name="author" content="Createx Studio" />
  {/* Viewport*/}
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {/* Favicon and Touch Icons*/}
  <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png" />
  <link rel="manifest" href="site.webmanifest" />
  <link rel="mask-icon" color="#fe6a6a" href="safari-pinned-tab.svg" />
  <meta name="msapplication-TileColor" content="#ffffff" />
  <meta name="theme-color" content="#ffffff" />
  {/* Vendor Styles including: Font Icons, Plugins, etc.*/}
  <link rel="stylesheet" media="screen" href="vendor/simplebar/dist/simplebar.min.css" />
  <link rel="stylesheet" media="screen" href="vendor/tiny-slider/dist/tiny-slider.css" />
  {/* Main Theme Styles + Bootstrap*/}
  <link rel="stylesheet" media="screen" href="css/theme.min.css" />
</div>

      <body className={inter.className}>{children}</body>


      <script src="vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="vendor/simplebar/dist/simplebar.min.js"></script>
    <script src="vendor/tiny-slider/dist/min/tiny-slider.js"></script>
    <script src="vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    <script src="js/theme.min.js"></script>
    </html>
  );
}
